### ISSUE TITLE
Please correspond to Composer

### ISSUE THREAD

**Issue by fuyutsuki** [michaelmawhinney/cryptex#1]

**Comment by michaelmawhinney** [comment]
I'll add namespacing and conform to PSR-4 standards. Then I can get the package registered on Packagist for user via Composer.

**Comment by fuyutsuki** [comment]
thanks!

**Comment by michaelmawhinney** [comment]
@fuyutsuki Cryptex class can now be installed via Composer:

`composer require michaelmawhinney/cryptex`

Cheers
